/** Catálogo canônico ~60 condomínios/hotéis Caldas Novas (PR 22B). */
export interface EmpreendimentoCatalogoItem {
  nomeOficial: string;
  slug: string;
  hotelId: string;
  websiteContentId?: string;
}

export const CALDAS_EMPREENDIMENTOS_CATALOGO: EmpreendimentoCatalogoItem[] = [
  { nomeOficial: 'Águas da Fonte', slug: 'aguas-da-fonte', hotelId: 'aguas-da-fonte' },
  { nomeOficial: 'Atrium Thermas', slug: 'atrium-thermas', hotelId: 'atrium-thermas' },
  { nomeOficial: 'Aldeia do Lago', slug: 'aldeia-do-lago', hotelId: 'aldeia-do-lago' },
  { nomeOficial: 'Alta Vista Thermas', slug: 'alta-vista-thermas', hotelId: 'alta-vista-thermas' },
  { nomeOficial: 'Aquarius Residence', slug: 'aquarius-residence', hotelId: 'aquarius-residence' },
  { nomeOficial: 'Araras Apart Service', slug: 'araras-apart-service', hotelId: 'araras-apart-service' },
  { nomeOficial: 'Boulevard Privé Suite Hotel', slug: 'boulevard-prive', hotelId: 'boulevard-prive' },
  { nomeOficial: 'Casa da Madeira', slug: 'casa-da-madeira', hotelId: 'casa-da-madeira' },
  { nomeOficial: 'DiRoma Exclusive', slug: 'diroma-exclusive', hotelId: 'diroma-exclusive' },
  { nomeOficial: 'Ecologic Park', slug: 'ecologic-park', hotelId: 'ecologic-park' },
  { nomeOficial: 'Ecologic Ville Resort', slug: 'ecologic-ville', hotelId: 'ecologic-ville' },
  { nomeOficial: 'Eldorado Flat', slug: 'eldorado-flat', hotelId: 'eldorado-flat' },
  { nomeOficial: 'Everest Flat Service', slug: 'everest-flat', hotelId: 'everest-flat' },
  { nomeOficial: 'Fiore Prime Flat', slug: 'fiore-prime', hotelId: 'fiore-prime' },
  { nomeOficial: 'Fiori DiRoma', slug: 'fiori-diroma', hotelId: 'fiori-diroma' },
  { nomeOficial: 'Golden Dolphin Gran Hotel', slug: 'golden-dolphin-gran', hotelId: 'golden-dolphin-gran' },
  { nomeOficial: 'Golden Dolphin Express', slug: 'golden-dolphin-express', hotelId: 'golden-dolphin-express' },
  { nomeOficial: 'Hotel Marina Flat', slug: 'hotel-marina', hotelId: 'hotel-marina' },
  { nomeOficial: 'Hotel Parque das Primaveras', slug: 'hotel-parque-primaveras', hotelId: 'hotel-parque-primaveras' },
  { nomeOficial: 'HotSprings B3 Hotéis', slug: 'hotsprings-b3', hotelId: 'hotsprings-b3' },
  { nomeOficial: 'Ilhas do Lago', slug: 'ilhas-do-lago', hotelId: 'ilhas-do-lago' },
  { nomeOficial: 'Império Romano', slug: 'imperio-romano', hotelId: 'imperio-romano' },
  { nomeOficial: 'Lacqua DiRoma', slug: 'lacqua-di-roma', hotelId: 'lacqua-di-roma' },
  { nomeOficial: 'Lagoa Eco Towers', slug: 'lagoa-eco-towers', hotelId: 'lagoa-eco-towers' },
  { nomeOficial: 'Lagoa Quente Hotel', slug: 'lagoa-quente', hotelId: 'lagoa-quente' },
  { nomeOficial: 'Le Jardin Suítes', slug: 'le-jardin', hotelId: 'le-jardin' },
  { nomeOficial: 'Paradise Flat Residence', slug: 'paradise-flat', hotelId: 'paradise-flat' },
  { nomeOficial: 'Parque Veredas', slug: 'parque-veredas', hotelId: 'parque-veredas' },
  { nomeOficial: 'Piazza DiRoma', slug: 'piazza-diroma', hotelId: 'piazza-diroma' },
  { nomeOficial: 'Praias do Lago Eco Resort', slug: 'praias-do-lago', hotelId: 'praias-do-lago' },
  { nomeOficial: 'Privé das Thermas', slug: 'prive-das-thermas', hotelId: 'prive-das-thermas' },
  { nomeOficial: 'Recanto do Bosque', slug: 'recanto-do-bosque', hotelId: 'recanto-do-bosque' },
  { nomeOficial: 'Recanto do Bosque Flat Service', slug: 'recanto-do-bosque-flat', hotelId: 'recanto-do-bosque-flat' },
  { nomeOficial: 'Resort do Lago', slug: 'resort-do-lago', hotelId: 'resort-do-lago' },
  { nomeOficial: 'Rio das Pedras Thermas Hotel', slug: 'rio-das-pedras', hotelId: 'rio-das-pedras' },
  { nomeOficial: 'Riviera Park Hotel', slug: 'riviera', hotelId: 'riviera' },
  { nomeOficial: 'Spazzio DiRoma', slug: 'spazzio-diroma', hotelId: 'spazzio-diroma' },
  { nomeOficial: 'Thermas do Bandeirante', slug: 'thermas-bandeirante', hotelId: 'thermas-bandeirante' },
  { nomeOficial: 'Thermas Place', slug: 'thermas-place', hotelId: 'thermas-place' },
  { nomeOficial: 'Hotel Santa Clara', slug: 'hotel-santa-clara', hotelId: 'hotel-santa-clara' },
  { nomeOficial: 'Villas DiRoma', slug: 'villas-diroma', hotelId: 'villas-diroma' },
  { nomeOficial: 'Hotel Morada das Águas', slug: 'morada-das-aguas', hotelId: 'morada-das-aguas' },
  { nomeOficial: 'Encontro das Águas Thermas Resort', slug: 'encontro-das-aguas', hotelId: 'encontro-das-aguas' },
  { nomeOficial: 'Park Lacqua DiRoma', slug: 'park-lacqua-diroma', hotelId: 'park-lacqua-diroma' },
  { nomeOficial: 'Thermas Lacqua DiRoma', slug: 'thermas-lacqua-diroma', hotelId: 'thermas-lacqua-diroma' },
  { nomeOficial: 'Resort Thermas Park', slug: 'resort-thermas-park', hotelId: 'resort-thermas-park' },
  { nomeOficial: 'Privé Praias do Lago', slug: 'prive-praias-do-lago', hotelId: 'prive-praias-do-lago' },
  { nomeOficial: 'Privé Ilhas do Lago', slug: 'prive-ilhas-do-lago', hotelId: 'prive-ilhas-do-lago' },
  { nomeOficial: 'Nutico Praia Clube Resort', slug: 'nutico-praia-clube', hotelId: 'nutico-praia-clube' },
  { nomeOficial: 'Evian Thermas Residence', slug: 'evian-thermas', hotelId: 'evian-thermas' },
  { nomeOficial: 'Millennium Thermas Residence', slug: 'millennium-thermas', hotelId: 'millennium-thermas' },
  { nomeOficial: 'Via Lacqua DiRoma', slug: 'via-lacqua-diroma', hotelId: 'via-lacqua-diroma' },
  { nomeOficial: 'Suites HotSprings', slug: 'suites-hotsprings', hotelId: 'suites-hotsprings' },
  { nomeOficial: 'The Villeneuve Residence', slug: 'the-villeneuve', hotelId: 'the-villeneuve' },
  { nomeOficial: 'Hotel Taiyo Premium', slug: 'hotel-taiyo-premium', hotelId: 'hotel-taiyo-premium' },
  { nomeOficial: 'Privé Lago dos Cisnes', slug: 'prive-lago-dos-cisnes', hotelId: 'prive-lago-dos-cisnes' },
  { nomeOficial: 'Hotel Águas Quentes', slug: 'hotel-aguas-quentes', hotelId: 'hotel-aguas-quentes' },
  { nomeOficial: 'Park Lago Club Hotel', slug: 'park-lago-club', hotelId: 'park-lago-club' },
  { nomeOficial: 'Vila Abaeté', slug: 'vila-abaete', hotelId: 'vila-abaete' },
  { nomeOficial: 'Caldas Palace Hotel', slug: 'caldas-palace', hotelId: 'caldas-palace' },
  { nomeOficial: 'Thermas Paradise Hotel', slug: 'thermas-paradise', hotelId: 'thermas-paradise' },
  { nomeOficial: 'Hotel CTC', slug: 'hotel-ctc', hotelId: 'hotel-ctc' },
  { nomeOficial: 'Thermas diRoma Hotel', slug: 'thermas-diroma-hotel', hotelId: 'thermas-diroma-hotel' },
  { nomeOficial: 'Flat Service Thermas do Bosque', slug: 'flat-thermas-bosque', hotelId: 'flat-thermas-bosque' },
];
