import { pgTable, serial, varchar, text, numeric, boolean, timestamp, integer, time, jsonb, decimal } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }),
  email: varchar('email', { length: 255 }),
  password: varchar('password', { length: 255 }),
  role: varchar('role', { length: 50 }),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const enterprises = pgTable('enterprises', {
  id: serial('id').primaryKey(),
  ownerId: integer('owner_id'),
  name: varchar('name', { length: 255 }).notNull(),
  legalName: varchar('legal_name', { length: 255 }),
  description: text('description'),
  enterpriseType: varchar('enterprise_type', { length: 50 }).notNull(),
  addressStreet: varchar('address_street', { length: 255 }),
  addressNumber: varchar('address_number', { length: 50 }),
  addressComplement: varchar('address_complement', { length: 255 }),
  addressNeighborhood: varchar('address_neighborhood', { length: 255 }),
  addressCity: varchar('address_city', { length: 255 }).notNull(),
  addressState: varchar('address_state', { length: 2 }).notNull(),
  addressZipCode: varchar('address_zip_code', { length: 20 }),
  addressCountry: varchar('address_country', { length: 100 }).default('Brasil'),
  latitude: decimal('latitude', { precision: 10, scale: 8 }),
  longitude: decimal('longitude', { precision: 11, scale: 8 }),
  phone: varchar('phone', { length: 20 }),
  email: varchar('email', { length: 255 }),
  website: varchar('website', { length: 255 }),
  checkInTime: time('check_in_time').default('15:00'),
  checkOutTime: time('check_out_time').default('11:00'),
  cancellationPolicy: varchar('cancellation_policy', { length: 50 }).default('moderate'),
  status: varchar('status', { length: 50 }).default('active'),
  isFeatured: boolean('is_featured').default(false),
  logoUrl: varchar('logo_url', { length: 500 }),
  images: jsonb('images').default([]),
  amenities: jsonb('amenities').default([]),
  metadata: jsonb('metadata').default({}),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const properties = pgTable('properties', {
  id: serial('id').primaryKey(),
  enterpriseId: integer('enterprise_id').notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  propertyType: varchar('property_type', { length: 50 }).notNull(),
  roomNumber: varchar('room_number', { length: 50 }),
  floorNumber: integer('floor_number'),
  buildingName: varchar('building_name', { length: 255 }),
  bedrooms: integer('bedrooms').default(0),
  bathrooms: decimal('bathrooms', { precision: 3, scale: 1 }).default('0'),
  beds: integer('beds').default(0),
  maxGuests: integer('max_guests').notNull().default(1),
  areaSqm: decimal('area_sqm', { precision: 10, scale: 2 }),
  amenities: jsonb('amenities').default([]),
  basePricePerNight: decimal('base_price_per_night', { precision: 10, scale: 2 }),
  currency: varchar('currency', { length: 10 }).default('BRL'),
  cleaningFee: decimal('cleaning_fee', { precision: 10, scale: 2 }).default('0'),
  serviceFeePercentage: decimal('service_fee_percentage', { precision: 5, scale: 2 }),
  minStayNights: integer('min_stay_nights').default(1),
  maxStayNights: integer('max_stay_nights'),
  status: varchar('status', { length: 50 }).default('active'),
  isFeatured: boolean('is_featured').default(false),
  isInstantBook: boolean('is_instant_book').default(false),
  images: jsonb('images').default([]),
  metadata: jsonb('metadata').default({}),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const accommodations = pgTable('accommodations', {
  id: serial('id').primaryKey(),
  propertyId: integer('property_id').notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  accommodationType: varchar('accommodation_type', { length: 50 }).notNull(),
  roomNumber: varchar('room_number', { length: 50 }),
  floorNumber: integer('floor_number'),
  bedrooms: integer('bedrooms').default(0),
  bathrooms: decimal('bathrooms', { precision: 3, scale: 1 }).default('0'),
  beds: integer('beds').default(0),
  bedType: varchar('bed_type', { length: 50 }),
  maxGuests: integer('max_guests').notNull().default(1),
  areaSqm: decimal('area_sqm', { precision: 10, scale: 2 }),
  amenities: jsonb('amenities').default([]),
  basePricePerNight: decimal('base_price_per_night', { precision: 10, scale: 2 }),
  currency: varchar('currency', { length: 10 }).default('BRL'),
  cleaningFee: decimal('cleaning_fee', { precision: 10, scale: 2 }).default('0'),
  minStayNights: integer('min_stay_nights').default(1),
  maxStayNights: integer('max_stay_nights'),
  status: varchar('status', { length: 50 }).default('active'),
  isFeatured: boolean('is_featured').default(false),
  isInstantBook: boolean('is_instant_book').default(false),
  images: jsonb('images').default([]),
  metadata: jsonb('metadata').default({}),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});