CREATE TABLE "accommodations" (
	"id" serial PRIMARY KEY NOT NULL,
	"property_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"accommodation_type" varchar(50) NOT NULL,
	"room_number" varchar(50),
	"floor_number" integer,
	"bedrooms" integer DEFAULT 0,
	"bathrooms" numeric(3, 1) DEFAULT '0',
	"beds" integer DEFAULT 0,
	"bed_type" varchar(50),
	"max_guests" integer DEFAULT 1 NOT NULL,
	"area_sqm" numeric(10, 2),
	"amenities" jsonb DEFAULT '[]'::jsonb,
	"base_price_per_night" numeric(10, 2),
	"currency" varchar(10) DEFAULT 'BRL',
	"cleaning_fee" numeric(10, 2) DEFAULT '0',
	"min_stay_nights" integer DEFAULT 1,
	"max_stay_nights" integer,
	"status" varchar(50) DEFAULT 'active',
	"is_featured" boolean DEFAULT false,
	"is_instant_book" boolean DEFAULT false,
	"images" jsonb DEFAULT '[]'::jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "enterprises" (
	"id" serial PRIMARY KEY NOT NULL,
	"owner_id" integer,
	"name" varchar(255) NOT NULL,
	"legal_name" varchar(255),
	"description" text,
	"enterprise_type" varchar(50) NOT NULL,
	"address_street" varchar(255),
	"address_number" varchar(50),
	"address_complement" varchar(255),
	"address_neighborhood" varchar(255),
	"address_city" varchar(255) NOT NULL,
	"address_state" varchar(2) NOT NULL,
	"address_zip_code" varchar(20),
	"address_country" varchar(100) DEFAULT 'Brasil',
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"phone" varchar(20),
	"email" varchar(255),
	"website" varchar(255),
	"check_in_time" time DEFAULT '15:00',
	"check_out_time" time DEFAULT '11:00',
	"cancellation_policy" varchar(50) DEFAULT 'moderate',
	"status" varchar(50) DEFAULT 'active',
	"is_featured" boolean DEFAULT false,
	"logo_url" varchar(500),
	"images" jsonb DEFAULT '[]'::jsonb,
	"amenities" jsonb DEFAULT '[]'::jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "properties" (
	"id" serial PRIMARY KEY NOT NULL,
	"enterprise_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"property_type" varchar(50) NOT NULL,
	"room_number" varchar(50),
	"floor_number" integer,
	"building_name" varchar(255),
	"bedrooms" integer DEFAULT 0,
	"bathrooms" numeric(3, 1) DEFAULT '0',
	"beds" integer DEFAULT 0,
	"max_guests" integer DEFAULT 1 NOT NULL,
	"area_sqm" numeric(10, 2),
	"amenities" jsonb DEFAULT '[]'::jsonb,
	"base_price_per_night" numeric(10, 2),
	"currency" varchar(10) DEFAULT 'BRL',
	"cleaning_fee" numeric(10, 2) DEFAULT '0',
	"service_fee_percentage" numeric(5, 2),
	"min_stay_nights" integer DEFAULT 1,
	"max_stay_nights" integer,
	"status" varchar(50) DEFAULT 'active',
	"is_featured" boolean DEFAULT false,
	"is_instant_book" boolean DEFAULT false,
	"images" jsonb DEFAULT '[]'::jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255),
	"password" varchar(255),
	"role" varchar(50),
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "branding" (
	"id" serial PRIMARY KEY NOT NULL,
	"company_name" varchar(255) NOT NULL,
	"tagline" varchar(500),
	"logo_url" text,
	"favicon_url" text,
	"primary_color" varchar(7) DEFAULT '#1E40AF',
	"secondary_color" varchar(7) DEFAULT '#F59E0B',
	"accent_color" varchar(7) DEFAULT '#10B981',
	"phone" varchar(20),
	"email" varchar(255),
	"whatsapp" varchar(20),
	"instagram" varchar(255),
	"facebook" varchar(255),
	"website" varchar(255),
	"address" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "parks" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255),
	"description" text,
	"type" varchar(50) NOT NULL,
	"category" varchar(50),
	"city" varchar(100),
	"state" varchar(2),
	"address" text,
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"image_url" text,
	"gallery_urls" text,
	"phone" varchar(20),
	"website" varchar(255),
	"opening_hours" text,
	"price_from" numeric(10, 2),
	"rating" numeric(3, 2),
	"total_reviews" integer DEFAULT 0,
	"enterprise_id" integer,
	"is_active" boolean DEFAULT true,
	"is_featured" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "parks_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "attractions" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255),
	"description" text,
	"type" varchar(50) NOT NULL,
	"category" varchar(50),
	"city" varchar(100),
	"state" varchar(2),
	"address" text,
	"latitude" numeric(10, 7),
	"longitude" numeric(10, 7),
	"image_url" text,
	"gallery_urls" text,
	"price_from" numeric(10, 2),
	"is_free" boolean DEFAULT false,
	"rating" numeric(3, 2),
	"total_reviews" integer DEFAULT 0,
	"park_id" integer,
	"enterprise_id" integer,
	"is_active" boolean DEFAULT true,
	"is_featured" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "attractions_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "promotions" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255),
	"description" text,
	"type" varchar(50) NOT NULL,
	"discount_type" varchar(20),
	"discount_value" numeric(10, 2),
	"coupon_code" varchar(50),
	"image_url" text,
	"start_date" date,
	"end_date" date,
	"min_purchase" numeric(10, 2),
	"max_uses" integer,
	"current_uses" integer DEFAULT 0,
	"product_id" integer,
	"enterprise_id" integer,
	"is_active" boolean DEFAULT true,
	"is_featured" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "promotions_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "travel_packages" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255),
	"description" text,
	"type" varchar(50) NOT NULL,
	"origin" varchar(100),
	"destination" varchar(100) NOT NULL,
	"departure_date" date,
	"return_date" date,
	"duration_days" integer,
	"duration_nights" integer,
	"price_per_person" numeric(10, 2) NOT NULL,
	"price_child" numeric(10, 2),
	"max_passengers" integer,
	"current_passengers" integer DEFAULT 0,
	"includes" text,
	"not_includes" text,
	"itinerary" text,
	"image_url" text,
	"gallery_urls" text,
	"rating" numeric(3, 2),
	"total_reviews" integer DEFAULT 0,
	"enterprise_id" integer,
	"is_active" boolean DEFAULT true,
	"is_featured" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "travel_packages_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "recommendations" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"type" varchar(50) NOT NULL,
	"category" varchar(50),
	"target_audience" varchar(50),
	"product_ids" text,
	"total_price" numeric(10, 2),
	"discounted_price" numeric(10, 2),
	"savings_percent" numeric(5, 2),
	"image_url" text,
	"priority" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"is_featured" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "popular_searches" (
	"id" serial PRIMARY KEY NOT NULL,
	"term" varchar(255) NOT NULL,
	"search_count" integer DEFAULT 0,
	"category" varchar(50),
	"last_searched_at" timestamp DEFAULT now(),
	CONSTRAINT "popular_searches_term_unique" UNIQUE("term")
);
--> statement-breakpoint
CREATE TABLE "search_history" (
	"id" serial PRIMARY KEY NOT NULL,
	"query" varchar(500) NOT NULL,
	"category" varchar(50),
	"destination" varchar(100),
	"results_count" integer DEFAULT 0,
	"user_id" integer,
	"session_id" varchar(255),
	"ip_address" varchar(45),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "leads" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone" varchar(20),
	"whatsapp" varchar(20),
	"cpf" varchar(14),
	"source" varchar(50) NOT NULL,
	"interest" varchar(100),
	"destination" varchar(100),
	"message" text,
	"status" varchar(20) DEFAULT 'novo',
	"assigned_to" varchar(255),
	"notes" text,
	"is_active" boolean DEFAULT true,
	"converted_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
