-- PR A: catalogo de atracoes para Roteiro Inteligente (motor inerte ate PR B)
CREATE TABLE IF NOT EXISTS roteiro_atracoes (
  id serial PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  nome text NOT NULL,
  tipo text NOT NULL,
  turnos jsonb NOT NULL DEFAULT '[]'::jsonb,
  dias_funcionamento jsonb NOT NULL DEFAULT '[]'::jsonb,
  publico text NOT NULL DEFAULT 'todos',
  faixa_preco text,
  descricao text,
  dica text,
  endereco text,
  lat numeric(9, 6),
  lng numeric(9, 6),
  imagem_url text,
  ordem integer NOT NULL DEFAULT 0,
  ativo boolean NOT NULL DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  criado_em timestamptz DEFAULT now(),
  atualizado_em timestamptz DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS idx_roteiro_atracoes_ativo_ordem
  ON roteiro_atracoes (ativo, ordem);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS idx_roteiro_atracoes_tipo
  ON roteiro_atracoes (tipo);
--> statement-breakpoint
-- Seed Caldas Novas — dias_funcionamento validados em fontes turisticas (corpo do PR A)
-- imagem_url NULL (politica anti-OTA; PR B adiciona assets proprios)
INSERT INTO roteiro_atracoes (
  slug, nome, tipo, turnos, dias_funcionamento, publico, faixa_preco,
  descricao, dica, endereco, lat, lng, imagem_url, ordem, ativo
) VALUES
(
  'serra-de-caldas',
  'Serra de Caldas',
  'passeio',
  '["manha","tarde"]'::jsonb,
  '["dom","seg","ter","qua","qui","sex","sab"]'::jsonb,
  'todos',
  'gratuito',
  'Mirantes e trilhas leves com vista da regiao termal.',
  'Leve agua e calcado confortavel; horario diurno recomendado pelo parque estadual.',
  'Parque Estadual da Serra de Caldas, Caldas Novas - GO',
  -17.758900,
  -48.629400,
  NULL,
  10,
  true
),
(
  'jardim-japones',
  'Jardim Japones',
  'passeio',
  '["manha"]'::jsonb,
  '["dom","seg","ter","qua","qui","sex","sab"]'::jsonb,
  'todos',
  'gratuito',
  'Jardim tematico no complexo da Serra de Caldas.',
  'Visita matinal evita sol forte; acesso pelo mesmo eixo do parque estadual.',
  'Parque Estadual da Serra de Caldas, Caldas Novas - GO',
  -17.759500,
  -48.628800,
  NULL,
  20,
  true
),
(
  'feira-do-luar',
  'Feira do Luar',
  'feira',
  '["noite"]'::jsonb,
  '["sab"]'::jsonb,
  'todos',
  'economico',
  'Feira de artesanato e gastronomia local aos sabados.',
  'Tradicionalmente aos sabados a noite (18h-23h); confirmar no local em feriados.',
  'R. Cel. Cirilo, Centro, Caldas Novas - GO',
  -17.744200,
  -48.627800,
  NULL,
  30,
  true
),
(
  'monumento-das-aguas',
  'Monumento das Aguas',
  'monumento',
  '["manha","tarde"]'::jsonb,
  '["dom","seg","ter","qua","qui","sex","sab"]'::jsonb,
  'todos',
  'gratuito',
  'Marco simbolico das aguas termais de Caldas Novas.',
  'Ponto fotografico rapido; ideal entre manha e inicio da tarde.',
  'Av. Goias, Centro, Caldas Novas - GO',
  -17.742800,
  -48.625900,
  NULL,
  40,
  true
),
(
  'praca-da-matriz',
  'Praca da Matriz',
  'monumento',
  '["manha","noite"]'::jsonb,
  '["dom","seg","ter","qua","qui","sex","sab"]'::jsonb,
  'todos',
  'gratuito',
  'Praca central com igreja matriz e comercio ao redor.',
  'Ambiente familiar de dia; movimento moderado a noite no centro.',
  'Praca da Matriz, Centro, Caldas Novas - GO',
  -17.743500,
  -48.626500,
  NULL,
  50,
  true
),
(
  'caldas-shopping',
  'Caldas Shopping',
  'shopping',
  '["tarde","noite"]'::jsonb,
  '["seg","ter","qua","qui","sex","sab","dom"]'::jsonb,
  'todos',
  'medio',
  'Shopping com cinema, praça de alimentacao e lojas.',
  'Horario tipico de shopping center (10h-22h); domingos com horario reduzido.',
  'Av. Coronel Cirilo, Caldas Novas - GO',
  -17.735600,
  -48.620100,
  NULL,
  60,
  true
),
(
  'restaurante-panela-quente',
  'Panela Quente Caldas',
  'restaurante',
  '["tarde"]'::jsonb,
  '["dom","seg","ter","qua","qui","sex","sab"]'::jsonb,
  'todos',
  'medio',
  'Almoco por quilo com pratos regionais.',
  'Turno de almoco (11h30-14h30); boa opcao entre passeios.',
  'Centro, Caldas Novas - GO',
  -17.744000,
  -48.627000,
  NULL,
  70,
  true
),
(
  'restaurante-boi-na-brasa',
  'Boi na Brasa',
  'restaurante',
  '["tarde"]'::jsonb,
  '["qui","sex","sab","dom"]'::jsonb,
  'familia',
  'medio',
  'Churrascaria e almoco em ambiente familiar.',
  'Fins de semana costumam ter maior movimento; reserva opcional.',
  'Regiao do Turista, Caldas Novas - GO',
  -17.738000,
  -48.622000,
  NULL,
  80,
  true
),
(
  'pizzaria-forno-vero',
  'Pizzaria Forno Vero',
  'restaurante',
  '["noite"]'::jsonb,
  '["ter","qua","qui","sex","sab","dom"]'::jsonb,
  'todos',
  'medio',
  'Pizzaria artesanal para jantar.',
  'Alternativa noturna quando a Feira do Luar nao ocorre no dia.',
  'Centro, Caldas Novas - GO',
  -17.743000,
  -48.626800,
  NULL,
  90,
  true
),
(
  'bar-choperia-centro',
  'Choperia do Centro',
  'restaurante',
  '["noite"]'::jsonb,
  '["sex","sab"]'::jsonb,
  'casal',
  'medio',
  'Bar e choppe para casal apos o jantar.',
  'Fins de semana; combina com estadia romantica.',
  'Centro, Caldas Novas - GO',
  -17.743800,
  -48.627200,
  NULL,
  100,
  true
),
(
  'parque-aquatico-dia-inteiro',
  'Parque Aquatico (dia inteiro)',
  'parque',
  '["dia_inteiro"]'::jsonb,
  '["dom","seg","ter","qua","qui","sex","sab"]'::jsonb,
  'familia',
  'alto',
  'Dia dedicado ao parque aquatico termal.',
  'Ocupa manha e tarde; planeje descanso a noite.',
  'Regiao Turistica, Caldas Novas - GO',
  -17.732000,
  -48.618000,
  NULL,
  110,
  true
),
(
  'relax-piscina-termal',
  'Relax no Hotel — Piscina Termal',
  'relax_hotel',
  '["tarde"]'::jsonb,
  '["dom","seg","ter","qua","qui","sex","sab"]'::jsonb,
  'todos',
  'incluso',
  'Tarde leve nas piscinas termais do hotel.',
  'Requer amenidade piscina_termal no hotel selecionado.',
  NULL,
  NULL,
  NULL,
  120,
  true
),
(
  'relax-area-kids',
  'Relax no Hotel — Area Kids',
  'relax_hotel',
  '["tarde"]'::jsonb,
  '["dom","seg","ter","qua","qui","sex","sab"]'::jsonb,
  'familia',
  'incluso',
  'Tarde no espaco kids do hotel.',
  'Requer amenidade area_kids no hotel selecionado.',
  NULL,
  NULL,
  NULL,
  130,
  true
)
ON CONFLICT (slug) DO NOTHING;
